# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-19.16

# Local packages, usually specified by relative directory name
packages:
- perfect-hash-generator
- phg-diagrams
- collision-diagrams

ghc-options:
  "$locals": -fwrite-ide-info

#The intention of this option is to prevent file permission problems, for example as the result of a stack command executed under sudo.
allow-different-user: true
