name: perfect-hash-generator-diagrams
version: '0.1.0.0'
synopsis: Diagrams for PHG
description: ! '
Generate documentation diagrams for Perfect Hash Generator
'

author: Karl Ostmo <kostmo@gmail.com>
maintainer: Karl Ostmo <kostmo@gmail.com>
category: Data Structures, Embedded
github: kostmo/perfect-hash-generator
license: Apache-2.0
license-file: LICENSE
ghc-options:
- -fwarn-tabs
- -W
dependencies:
- base >= 4.5 && < 5
- diagrams
- diagrams-lib

library:
  source-dirs: src
  dependencies:
  - containers
  - diagrams-lib

executables: 
  mk-diagram:
    main: Main.hs
    source-dirs:
    - mk-diagram
    dependencies:
    - diagrams
    - diagrams-svg
