name: perfect-hash-collision-diagrams
version: '0.1.0.0'
synopsis: Diagrams for PHG
description: ! '
Generate documentation diagrams for Perfect Hash Generator
'

author: Karl Ostmo <kostmo@gmail.com>
maintainer: Karl Ostmo <kostmo@gmail.com>
category: Data Structures, Embedded
github: kostmo/perfect-hash-generator
license: Apache-2.0
license-file: LICENSE
ghc-options:
- -fwarn-tabs
- -W
dependencies:
- base >= 4.5 && < 5

library:
  source-dirs: src
  dependencies:
  - diagrams-lib
  - diagrams-svg
  - diagrams-contrib
  - palette
  - matrix
  - perfect-hash-generator
  - split

executables:
  measure-hash-spread:
    main: Main.hs
    source-dirs:
    - hashing-spread
    dependencies:
    - perfect-hash-generator
    - perfect-hash-collision-diagrams
    - optparse-applicative
    - matrix
    - containers
    - diagrams-svg
    - diagrams-lib
    - palette
    - colour
    - random